controllers/AgentsController.php
<?php
namespace frontend\controllers;

use frontend\account\models\ProductsList;
use yii;
use yii\data\Pagination;
use yii\helpers\Url;
use yii\web\Controller;
use frontend\account\models\UserCompanies;
use frontend\account\models\Groups;
use frontend\account\models\User;
use frontend\models\Language;
use frontend\account\models\UserStatistics;
use frontend\models\UserVideos;
use frontend\account\models\ProductsCollections;
use frontend\models\CatalogCategories;

class AgentsController extends Controller
{
    private $role;
    private $user_id;
    private $language = "ru";

    public function init()
    {
        $this->user_id = Yii::$app->user->identity->id;
        $this->language = Language::getCurrent()->url;
        $this->role = Yii::$app->user->identity->roles;
    }

    public function actionIndex()
    {
        $request = Yii::$app->request;
        $session = Yii::$app->session;
        $session['agent_q_param'] = $request->get('q');
        $session['agent_column_name'] = $request->get('column');
        $pagination = new Pagination([
            'defaultPageSize' => '6',
            'totalCount' => User::countAgents($session['agent_column_name'], $session['agent_q_param']),
        ]);
        $agents = User::selectsAgents($pagination, $session['agent_column_name'], $session['agent_q_param']);
        $i = -1;
        foreach ($agents as $agent) {
            $i++;
            $agents[$i]['companies'] = UserCompanies::selectCountCompaniesByAgent($agent['id']);
            $companies_id = UserCompanies::getCompaniesByAgent($agent['id']);
            if ($companies_id)
                $agents[$i]['companies'] = ProductsList::countProductsByCompanyId($companies_id);
            $agents[$i]['products'] = UserCompanies::selectCountCompaniesByAgent($agent['id']);
        }
        return $this->render('index', [
            'agents' => $agents,
            'pagination' => $pagination
        ]);
    }

    public function actionProfile()
    {
        $this->setAgentStatistics();
        $id = Yii::$app->request->get('id', false);
        if ($id && User::findOne(['id' => $id, 'roles' => 'agent'])) {
            $statistic = UserStatistics::findOne(['id_user' => $id]);
            if ($statistic) {
                if ($this->role)
                    $column = $this->role;
                else
                    $column = 'guest';
                $temp = explode(",", $statistic[$column]);
                $temp[0] += 1;
                $month = date("n", time());
                if ($month == $statistic->month) {
                    $temp[1] += 1;
                } else {
                    $statistic->month = $month;
                    $temp[1] = 1;
                }

                $statistic[$column] = $temp[0] . ',' . $temp[1];
                $statistic->update();

            } else
                UserStatistics::createNewUserRow($id);

            list($controller) = Yii::$app->createController('about');
            list($agent) = Yii::$app->createController('account/profile-agent');

            if ($id != $this->user_id) {
                $click_action = true;
            } else $click_action = false;

            return $this->render('profile', [
                'user_information' => User::findOne(['id' => $id, 'roles' => 'agent']),
                'videos' => UserVideos::find()->where(['user_id' => $id])->all(),
                'reviews' => $controller->getUserReviews($id),
                'approved' => $agent->getApprovedConfirmationProjects($id, 6, 1),
                'click_action' => $click_action
            ]);
        } else
            Yii::$app->getResponse()->redirect(array('agents'));
    }

    public function setAgentStatistics()
    {
//        print_r($_SERVER['HTTP_REFERER']);
    }

}

views/agents/index.php
<?php
use yii\widgets\LinkPager;
use frontend\widgets\Banner;
use frontend\widgets\SideBar;
use yii\helpers\Url;

$this->title = 'Agents';
$this->params['breadcrumbs'][] = $this->title;

//var_dump($agents);
//die();
?>

    <!--START CONTENT-->
    <section class="catalog-id" data-id="1">
        <div class="container container-style-catalog scrollSidebar">
            <div class="row">

                <!--START CENTER-->
                <?php if (!Yii::$app->user->isGuest): ?>
                <style>
                    .left-sidebar {
                        padding-left: 0;
                        padding-top: 0;
                    }
                </style>
                <div class="col-lg-3 left-sidebar fixed">
                    <span class="sidebar-caption"><?= Yii::t('account', 'manage_account') ?></span>
                    <?= SideBar::widget(); ?>
                </div>
                <div class="col-lg-9 catalog-column profile-agent-comps centralScroll agents central-content">

                    <?php else: ?>

                    <div class="col-lg-12 catalog-column profile-agent-comps agents">
                        <?php endif; ?>
                        <div class="row">
                            <div class="content">
                                <div class="portfolio-top profile-conten-me ">
                                    <div class="catalog-box special-offers-catalog page-in-catalog">
                                        <div class="clearfix"></div>
                                        <h4 class="promote promote-bottom">Agents</h4>
<!--                                        <p class="upload-portfolio download-portfolio join">Add-->
<!--                                            <a href="#"></a>-->
<!--                                        </p>-->
                                        <div class="clearfix"></div>
                                        <form class="forma-input">
                                            <div class="search">
                                                <div class="input-edit">
                                                    <div class="input-container">
                                                        <input class="text-input floating-label" name="q"
                                                               type="text" value="">
                                                        <label for="sample1">Search</label>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="selects">
                                                <select name="column">
                                                    <option value="name">Search by</option>
                                                    <option value="name">Name</option>
                                                    <option value="country">Country</option>
                                                    <option value="company">Company</option>
                                                </select>
                                            </div>
                                        </form>
                                        <?php if ($agents) : ?>
                                        <div class="companys">
                                            <?php while ($agents): ?>
                                                <?php $agent = array_pop($agents); ?>

                                                <div class="company agents"
                                                     style="background-image: url('/images/pic_50.png');">
                                                    <a href="<?= Yii::$app->urlManager->createUrl(['agents/profile', 'id' => $agent['id']]) ?>"><img
                                                        class="company-img"
                                                        src="<?= Yii::getAlias('@avatar/' . $agent['avatar']) ?>"
                                                        alt="img"></a>
                                                    <div class="name-company">
                                                        <h5><?= $agent['first_name'] ?>
                                                            <span><?= $agent['last_name'] ?></span></h5>
                                                        <p><?= $agent['country'] ?></p>
                                                    </div>
                                                    <ul class="description">
                                                        <li>Manufacturers: <span><?= $agent['companies'] ?></span></li>
                                                        <li>Products: <span><?= $agent['products'] ?></span></li>
                                                    </ul>
                                                    <div class="author"><img
                                                            src="<?= Yii::getAlias('@avatar/' . $agent['logo']) ?>"
                                                            alt="#">
                                                        <p class="name"><?= $agent['company'] ?></p>
                                                    </div>
                                                </div>
                                            <?php endwhile; ?>
                                            <?php endif; ?>
                                            <div class="clearfix"></div>
                                            <div class="bread-crumbs">
                                                <?= LinkPager::widget(['pagination' => $pagination,
                                                    'disabledPageCssClass' => false,
                                                    'nextPageLabel' => '',
                                                    'prevPageLabel' => '',
                                                    'options' => ['class' => 'hvr-radial-out1, agent-pagination'],
                                                ]); ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
<?php
$this->registerJsFile('agent_js/agents.js', ['depends' => 'frontend\assets\AppAsset']);